feat: More information about error happened
SchweizerischeBundesbahnen/weasyprint-service pull request #44
Opened 2024-08-12 15:49 UTC by yurtsevich-sbb

Refs: #43

### Proposed changes

Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue using one of the [supported keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) here in this description (not in the title of the PR).

### Checklist

Before creating a PR, run through this checklist and mark each as complete:
- [x] I have read the [`CONTRIBUTING`](CONTRIBUTING.md) document
- [ ] If applicable, I have added tests that prove my fix is effective or that my feature works
- [x] If applicable, I have checked that any relevant tests pass after adding my changes
- [ ] I have updated any relevant documentation

2024-08-12 18:10 UTC, grigoriev approved these changes

2024-08-13 06:21 UTC, grigoriev approved these changes

2024-08-20 10:11 UTC, ariwk requested changes
there is no change in thin PR. Why?

2024-08-20 10:20 UTC, nirikash approved these changes

2024-08-20 11:51 UTC, closed without merging

2024-08-20 11:51 UTC, yurtsevich-sbb commented
Not relevant anymore, changes are applied via another branch/PR